"""new

Revision ID: 014b6c429483
Revises: 757f05760a85
Create Date: 2024-06-25 11:11:03.174595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014b6c429483'
down_revision: Union[str, None] = '757f05760a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('RatingUsers', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('RatingUsers', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###
