"""init

Revision ID: 757f05760a85
Revises:
Create Date: 2024-06-25 11:09:08.180447

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "757f05760a85"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "BannedStickers",
        sa.Column("set_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("set_name"),
    )
    op.create_table(
        "ChatAdmins",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id", "admin_id"),
    )
    op.create_table(
        "RatingUsers",
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "messageusers",
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("chat_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("message_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("user_id", "chat_id", "message_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messageusers")
    op.drop_table("RatingUsers")
    op.drop_table("ChatAdmins")
    op.drop_table("BannedStickers")
    # ### end Alembic commands ###
